[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono.workspace = true
uuid.workspace = true
bigdecimal.workspace = true

async-trait.workspace = true

serde.workspace = true
sqlx.workspace = true

anyhow.workspace = true

domain.workspace = true
application.workspace = true
