[package]
name = "presentation"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono.workspace = true
uuid.workspace = true
bigdecimal.workspace = true

tokio.workspace = true
serde.workspace = true
tower-http.workspace = true
axum.workspace = true
anyhow.workspace = true

application.workspace = true
