DROP TABLE IF EXISTS appointment_services;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS specialist_services;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS specialists;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS otps;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS users;
